public class GetCauseMethodDemo{
    // public static void main(String [] args) throws Exception{
    //     try{
    //         m1();
    //     }catch(Exception e){
    //         System.out.println("The EXception occur"+ e.getCause());
    //     }

    //     public static String m1() throws Exception{
    //         int arr[] = {1,2,3,4,5};
    //         try{
    //             arr[10] = 43;
    //         }
    //         catch(ArrayIndexOutOfBoundsException ae){
    //             Exception e = new Exception();
    //             e.initCause(ae);
    //             throw(e);
    //         }
    //     }
    // }
}